<?php

namespace Database\Seeders;

use App\Models\BancoProyecto;
use Illuminate\Database\Seeder;

class BancoProyectosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Datos reales del contrato 477_2021
        $proyectosReales = [
            [
                'codigo_elemento' => '30000744',
                'tramo_direccion' => 'KR 19 BIS E ENTRE CL 81A S Y CL 81C BIS S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '432.50248697870001',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '50005419',
                'tramo_direccion' => 'KR 18 E ENTRE CL 80B S Y CL 80C S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '122.2081373714',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '50005420',
                'tramo_direccion' => 'KR 18 E CL 80A S Y CL 80B S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '240.1893611962',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '50007905',
                'tramo_direccion' => 'KR 18 E ENTRE CL 81B S Y CL 82 S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '516.15112283810004',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003189',
                'tramo_direccion' => 'CL 80B S ENTRE KR 17 BIS E Y KR 18 E',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '93.539350303800006',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003272',
                'tramo_direccion' => 'KR 18 E ENTRE CL 80C S Y CL 80D S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '159.65166361550001',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003340',
                'tramo_direccion' => 'KR 17 E ENTRE CL 80B S Y CL 81BIS S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '628.264892315',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003359',
                'tramo_direccion' => 'KR 18 E ENTRE CL 80D S Y CL 81 BIS S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '424.02278398700003',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003402',
                'tramo_direccion' => 'KR 17 E ENTRE 81 BIS S Y CL 81A S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '133.7194211039',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003406',
                'tramo_direccion' => 'KR 18 E ENTRE CL 81 BIS S Y CL 81A S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '168.26304256200001',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003408',
                'tramo_direccion' => 'CL 81A S ENTRE KR 17 E Y KR 17A S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '212.65715233200001',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003428',
                'tramo_direccion' => 'KR 18 E ENTRE CL 81A S Y CL 81B S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '123.957903124',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003453',
                'tramo_direccion' => 'KR 17 E ENTRE CL 81A S Y CL 81B S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '162.5838222264',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003594',
                'tramo_direccion' => 'KR 17 E ENTRE CL 81B S Y CL 82 S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '743.85505844599993',
                'id_contrato' => '477_2021',
            ],
            [
                'codigo_elemento' => '5003620',
                'tramo_direccion' => 'KR 16 E ENTRE CL 81 BIS S Y CL 82 S',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'USME',
                'upl' => 'UPZ52',
                'barrio' => 'PARCELACION SAN PEDRO',
                'area_elemento' => '896.45963363199996',
                'id_contrato' => '477_2021',
            ],
        ];

        // Datos adicionales para demostración de gráficos (ficticios)
        $proyectosDemostracion = [
            // SUBA
            [
                'codigo_elemento' => 'SUB-001',
                'tramo_direccion' => 'AV SUBA CL 128 Y CL 129',
                'estado' => 'Completado',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'SUBA',
                'upl' => 'UPZ71',
                'barrio' => 'LA ALHAMBRA',
                'area_elemento' => '350.50',
                'id_contrato' => '450_2021',
            ],
            [
                'codigo_elemento' => 'SUB-002',
                'tramo_direccion' => 'CL 130 ENTRE KR 91 Y KR 92',
                'estado' => 'Completado',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'SUBA',
                'upl' => 'UPZ71',
                'barrio' => 'NIZA',
                'area_elemento' => '280.30',
                'id_contrato' => '450_2021',
            ],
            [
                'codigo_elemento' => 'SUB-003',
                'tramo_direccion' => 'KR 92 CL 131 Y CL 132',
                'estado' => 'En planificación',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'SUBA',
                'upl' => 'UPZ71',
                'barrio' => 'NIZA ANTIGUA',
                'area_elemento' => '420.75',
                'id_contrato' => '451_2021',
            ],
            // KENNEDY
            [
                'codigo_elemento' => 'KEN-001',
                'tramo_direccion' => 'AV BOYACA CL 38 SUR Y CL 40 SUR',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'KENNEDY',
                'upl' => 'UPZ82',
                'barrio' => 'PATIO BONITO',
                'area_elemento' => '550.20',
                'id_contrato' => '452_2021',
            ],
            [
                'codigo_elemento' => 'KEN-002',
                'tramo_direccion' => 'CL 38 SUR ENTRE KR 86 Y KR 87',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'KENNEDY',
                'upl' => 'UPZ82',
                'barrio' => 'LAS MARGARITAS',
                'area_elemento' => '310.45',
                'id_contrato' => '452_2021',
            ],
            [
                'codigo_elemento' => 'KEN-003',
                'tramo_direccion' => 'KR 86 CL 40 SUR Y CL 41 SUR',
                'estado' => 'Suspendido',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'KENNEDY',
                'upl' => 'UPZ82',
                'barrio' => 'KENNEDY CENTRAL',
                'area_elemento' => '230.60',
                'id_contrato' => '452_2021',
            ],
            [
                'codigo_elemento' => 'KEN-004',
                'tramo_direccion' => 'CL 41 SUR ENTRE KR 85 Y KR 86',
                'estado' => 'Completado',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'KENNEDY',
                'upl' => 'UPZ82',
                'barrio' => 'CARVAJAL',
                'area_elemento' => '390.80',
                'id_contrato' => '453_2021',
            ],
            // ENGATIVÁ
            [
                'codigo_elemento' => 'ENG-001',
                'tramo_direccion' => 'AV CALI CL 68 Y CL 70',
                'estado' => 'Completado',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'ENGATIVÁ',
                'upl' => 'UPZ73',
                'barrio' => 'BOLIVIA',
                'area_elemento' => '670.90',
                'id_contrato' => '454_2021',
            ],
            [
                'codigo_elemento' => 'ENG-002',
                'tramo_direccion' => 'CL 70 ENTRE KR 102 Y KR 103',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'ENGATIVÁ',
                'upl' => 'UPZ73',
                'barrio' => 'MINUTO DE DIOS',
                'area_elemento' => '340.50',
                'id_contrato' => '454_2021',
            ],
            [
                'codigo_elemento' => 'ENG-003',
                'tramo_direccion' => 'KR 103 CL 71 Y CL 72',
                'estado' => 'En planificación',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'ENGATIVÁ',
                'upl' => 'UPZ73',
                'barrio' => 'QUIRIGUA',
                'area_elemento' => '280.40',
                'id_contrato' => '455_2021',
            ],
            // CHAPINERO
            [
                'codigo_elemento' => 'CHP-001',
                'tramo_direccion' => 'CL 63 ENTRE KR 7 Y KR 9',
                'estado' => 'Completado',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'CHAPINERO',
                'upl' => 'UPZ99',
                'barrio' => 'CHAPINERO CENTRAL',
                'area_elemento' => '450.70',
                'id_contrato' => '456_2021',
            ],
            [
                'codigo_elemento' => 'CHP-002',
                'tramo_direccion' => 'KR 7 CL 64 Y CL 65',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'CHAPINERO',
                'upl' => 'UPZ99',
                'barrio' => 'PARDO RUBIO',
                'area_elemento' => '320.30',
                'id_contrato' => '456_2021',
            ],
            [
                'codigo_elemento' => 'CHP-003',
                'tramo_direccion' => 'CL 67 ENTRE KR 11 Y KR 13',
                'estado' => 'Completado',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'CHAPINERO',
                'upl' => 'UPZ99',
                'barrio' => 'CHICÓ LAGO',
                'area_elemento' => '380.90',
                'id_contrato' => '457_2021',
            ],
            // FONTIBÓN
            [
                'codigo_elemento' => 'FON-001',
                'tramo_direccion' => 'AV ELDORADO CL 26 Y CL 27',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'FONTIBÓN',
                'upl' => 'UPZ75',
                'barrio' => 'FONTIBÓN CENTRO',
                'area_elemento' => '890.50',
                'id_contrato' => '458_2021',
            ],
            [
                'codigo_elemento' => 'FON-002',
                'tramo_direccion' => 'CL 24 ENTRE KR 98 Y KR 100',
                'estado' => 'Suspendido',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'FONTIBÓN',
                'upl' => 'UPZ75',
                'barrio' => 'MODELIA',
                'area_elemento' => '340.20',
                'id_contrato' => '458_2021',
            ],
            // BOSA
            [
                'codigo_elemento' => 'BOS-001',
                'tramo_direccion' => 'AV BOSA CL 57 SUR Y CL 59 SUR',
                'estado' => 'En planificación',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'BOSA',
                'upl' => 'UPZ84',
                'barrio' => 'BOSA CENTRAL',
                'area_elemento' => '520.40',
                'id_contrato' => '459_2021',
            ],
            [
                'codigo_elemento' => 'BOS-002',
                'tramo_direccion' => 'CL 58 SUR ENTRE KR 78 Y KR 80',
                'estado' => 'Completado',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'BOSA',
                'upl' => 'UPZ84',
                'barrio' => 'SAN BERNARDINO',
                'area_elemento' => '410.60',
                'id_contrato' => '460_2021',
            ],
            [
                'codigo_elemento' => 'BOS-003',
                'tramo_direccion' => 'KR 79 CL 60 SUR Y CL 61 SUR',
                'estado' => 'En ejecución',
                'tipo_elemento_civ_rupi' => 'Vía',
                'localidad' => 'BOSA',
                'upl' => 'UPZ84',
                'barrio' => 'LAURELES',
                'area_elemento' => '290.30',
                'id_contrato' => '460_2021',
            ],
        ];

        // Insertar todos los proyectos
        $todosProyectos = array_merge($proyectosReales, $proyectosDemostracion);

        foreach ($todosProyectos as $proyecto) {
            BancoProyecto::create($proyecto);
        }

        $this->command->info('✓ ' . count($todosProyectos) . ' proyectos insertados correctamente');
        $this->command->info('  - ' . count($proyectosReales) . ' proyectos reales del contrato 477_2021');
        $this->command->info('  - ' . count($proyectosDemostracion) . ' proyectos de demostración');
    }
}
